version: '2.1'

services:
  postgres:
    image: postgres:15.2-alpine
    restart: always
    container_name: postgres-basic
    volumes:
      - airflow-db-data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - 32769:5432
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow_db
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "airflow_db",
          "-U",
          "airflow"
        ]
      timeout: 45s
      interval: 10s
      retries: 10
  airflow:
    build: '.'
    restart: always
    container_name: airflow-basic
    env_file:
      - .env
    volumes:
      - ./mnt/airflow/dags:/opt/airflow/dags
    ports:
      - 8080:8080

    healthcheck:
      test: [ "CMD", "nc", "-z", "airflow", "8080" ]
      interval: 10s
      timeout: 45s
      retries: 10
    depends_on:
      - postgres
volumes:
  airflowbasic-db-data:
